spring.application.name=auth-service

# DO NOT TOUCH - if you have any local changes, don't push them to the remote repository

# JWT
jwt.secret = ${JWT_SECRET}
jwt.access.expiration = 900000
jwt.refresh.expiration = 604800000

# Cookie
cookie.access.name = accessToken
cookie.access.path = /
cookie.access.max-age = 3600
cookie.refresh.name = refreshToken
cookie.refresh.path = /auth/refresh
cookie.refresh.max-age = 604800
cookie.http-only = true
cookie.secure = false
cookie.same-site = Lax

# User Service
user.service.url = http://user-service:8080
user.service.get-user-by-email = /users/email/{email}
user.service.get-user-password-by-id = /users/{id}/check-password
user.service.create = /users

# Redis
spring.data.redis.host = redis
spring.data.redis.port = 6379
spring.data.redis.password =

# Claims
jwt.claim.id = id
jwt.claim.role = role
jwt.claim.type = type
jwt.claim.token-type = access