# JWT Secret for tests
jwt.secret=test-secret-key-for-jwt-tests-that-is-at-least-32-bytes-long-for-testing

# JWT Header
# JWT Token
# Token Expiration
jwt.access.expiration=3600
jwt.refresh.expiration=86400

# Token Claims
jwt.claim.id=id
jwt.claim.role=role
jwt.claim.type=type
jwt.claim.token-type=access

# User Service URLs
user.service.get-user-by-email=/api/users/email/{email}
user.service.get-user-password-by-id=/api/users/{id}/password
user.service.create=/api/users
user.service.url = http://user-service:8080