version: '3.9'

services:
  frontend:
    container_name: frontend
    build: .
    entrypoint: ["/usr/sbin/nginx", "-g", "daemon off;"]
    restart: always
    ports:
      - "80:80"
    networks:
      - backend-net

networks:
  backend-net:
    external: true