version: '3.9'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - backend-net