version: '3.9'
services:
  gateway:
    image: n1vvas1e/gateway-service:v1
    container_name: gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
    networks:
      - backend-net

networks:
  backend-net:
    external: true