version: '3.9'

services:
  gateway:
    image: 'gateway'
    build: .
    container_name: gateway
    restart: on-failure

    ports:
      - "8080:8080"
    networks:
      - backend-net

networks:
  backend-net:
    external: true