server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        #Маршрут для AUTH-SERVICE
        - id: auth_route
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**

        #Маршрут для USER-SERVICE
        - id: user_route
          uri: http://user-service:8080
          predicates:
            - Path=/api/**
          filters:
            - name: AuthenticationFilter
              args:
                skipAuth: false

      #Настройка CORS для обращения из браузера
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

#Настройки JWT и секретов
jwt:
  secret: ${JWT_SECRET}
  claim:
    id: id
    type: type

internal:
  api:
    secret: ${INTERNAL_SECRET}

logging:
  level:
    ru.productallergen.gateway.filter: DEBUG