server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        #Маршрут для AUTH-SERVICE
        - id: auth_route
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        #Маршрут для USER-SERVICE
        - id: user_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
          filters:
            - name: AuthenticationFilter
              args:
                skipAuth: false

#Настройки JWT и секретов
jwt:
  secret: ${JWT_SECRET:SL7GFwbppwEoIXBHVH7k9hxzN3dpy5eZLsRghMZRFAE=}
  claim:
    id: id
    type: type

internal:
  api:
    secret: ${INTERNAL_SECRET:4f6174685365637265744b65793230323650726f64756374416c6c657267656e47617465776179}