export type CatalogFoodItem = {
  foodName: string;
  category: string;
  components: string[];
};

export const TOP_FOOD_CATALOG: CatalogFoodItem[] = [
  { foodName: 'Йогурт Даниссимо', category: 'DAIRY', components: ['йогурт', 'молоко', 'сахар', 'закваска', 'ароматизатор'] },
  { foodName: 'Йогурт греческий', category: 'DAIRY', components: ['молоко', 'закваска'] },
  { foodName: 'Кефир 1%', category: 'DAIRY', components: ['молоко', 'кефирные грибки'] },
  { foodName: 'Творог 5%', category: 'DAIRY', components: ['молоко', 'закваска'] },
  { foodName: 'Сыр Гауда', category: 'DAIRY', components: ['молоко', 'соль', 'закваска', 'фермент'] },
  { foodName: 'Сметана 15%', category: 'DAIRY', components: ['сливки', 'закваска'] },
  { foodName: 'Молоко пастеризованное', category: 'DAIRY', components: ['молоко'] },
  { foodName: 'Ряженка', category: 'DAIRY', components: ['топленое молоко', 'закваска'] },
  { foodName: 'Сливочное масло', category: 'DAIRY', components: ['сливки', 'соль'] },
  { foodName: 'Сыр моцарелла', category: 'DAIRY', components: ['молоко', 'закваска', 'фермент', 'соль'] },

  { foodName: 'Яблоко', category: 'FRUIT', components: ['яблоко'] },
  { foodName: 'Банан', category: 'FRUIT', components: ['банан'] },
  { foodName: 'Груша', category: 'FRUIT', components: ['груша'] },
  { foodName: 'Апельсин', category: 'FRUIT', components: ['апельсин'] },
  { foodName: 'Мандарин', category: 'FRUIT', components: ['мандарин'] },
  { foodName: 'Киви', category: 'FRUIT', components: ['киви'] },
  { foodName: 'Виноград', category: 'FRUIT', components: ['виноград'] },
  { foodName: 'Персик', category: 'FRUIT', components: ['персик'] },
  { foodName: 'Ананас', category: 'FRUIT', components: ['ананас'] },
  { foodName: 'Клубника', category: 'FRUIT', components: ['клубника'] },

  { foodName: 'Огурец', category: 'VEGETABLE', components: ['огурец'] },
  { foodName: 'Помидор', category: 'VEGETABLE', components: ['помидор'] },
  { foodName: 'Морковь', category: 'VEGETABLE', components: ['морковь'] },
  { foodName: 'Картофель', category: 'VEGETABLE', components: ['картофель'] },
  { foodName: 'Свекла', category: 'VEGETABLE', components: ['свекла'] },
  { foodName: 'Капуста белокочанная', category: 'VEGETABLE', components: ['капуста'] },
  { foodName: 'Брокколи', category: 'VEGETABLE', components: ['брокколи'] },
  { foodName: 'Кабачок', category: 'VEGETABLE', components: ['кабачок'] },
  { foodName: 'Болгарский перец', category: 'VEGETABLE', components: ['перец'] },
  { foodName: 'Лук репчатый', category: 'VEGETABLE', components: ['лук'] },

  { foodName: 'Куриная грудка', category: 'MEAT', components: ['курица'] },
  { foodName: 'Индейка филе', category: 'MEAT', components: ['индейка'] },
  { foodName: 'Говядина отварная', category: 'MEAT', components: ['говядина', 'соль'] },
  { foodName: 'Свинина запеченная', category: 'MEAT', components: ['свинина', 'соль', 'специи'] },
  { foodName: 'Котлета куриная', category: 'MEAT', components: ['куриный фарш', 'лук', 'яйцо', 'соль'] },
  { foodName: 'Тефтели', category: 'MEAT', components: ['фарш', 'рис', 'лук', 'соль'] },
  { foodName: 'Пельмени', category: 'MEAT', components: ['мука', 'вода', 'фарш', 'лук', 'соль'] },
  { foodName: 'Сосиски', category: 'MEAT', components: ['мясо', 'соль', 'специи', 'консерванты'] },
  { foodName: 'Колбаса вареная', category: 'MEAT', components: ['мясо', 'соль', 'нитрит натрия'] },
  { foodName: 'Бекон', category: 'MEAT', components: ['свинина', 'соль', 'специи'] },

  { foodName: 'Лосось запеченный', category: 'FISH', components: ['лосось', 'соль'] },
  { foodName: 'Тунец консервированный', category: 'FISH', components: ['тунец', 'масло', 'соль'] },
  { foodName: 'Скумбрия', category: 'FISH', components: ['скумбрия', 'соль'] },
  { foodName: 'Треска', category: 'FISH', components: ['треска'] },
  { foodName: 'Креветки', category: 'FISH', components: ['креветки', 'соль'] },
  { foodName: 'Крабовые палочки', category: 'FISH', components: ['рыбный белок', 'крахмал', 'соль', 'ароматизатор'] },
  { foodName: 'Селедка', category: 'FISH', components: ['сельдь', 'соль'] },
  { foodName: 'Икра красная', category: 'FISH', components: ['икра', 'соль', 'консервант'] },
  { foodName: 'Мидии', category: 'FISH', components: ['мидии'] },
  { foodName: 'Минтай', category: 'FISH', components: ['минтай'] },

  { foodName: 'Гречка', category: 'GRAINS', components: ['гречка', 'вода', 'соль'] },
  { foodName: 'Рис отварной', category: 'GRAINS', components: ['рис', 'вода', 'соль'] },
  { foodName: 'Овсянка на воде', category: 'GRAINS', components: ['овсяные хлопья', 'вода'] },
  { foodName: 'Овсянка на молоке', category: 'GRAINS', components: ['овсяные хлопья', 'молоко', 'сахар'] },
  { foodName: 'Булгур', category: 'GRAINS', components: ['булгур', 'вода', 'соль'] },
  { foodName: 'Киноа', category: 'GRAINS', components: ['киноа', 'вода'] },
  { foodName: 'Перловка', category: 'GRAINS', components: ['перловка', 'вода', 'соль'] },
  { foodName: 'Макароны', category: 'GRAINS', components: ['мука', 'вода', 'яйцо'] },
  { foodName: 'Спагетти', category: 'GRAINS', components: ['мука твердых сортов', 'вода'] },
  { foodName: 'Пшено', category: 'GRAINS', components: ['пшено', 'вода'] },

  { foodName: 'Фасоль', category: 'LEGUMES', components: ['фасоль', 'вода', 'соль'] },
  { foodName: 'Чечевица', category: 'LEGUMES', components: ['чечевица', 'вода', 'соль'] },
  { foodName: 'Нут', category: 'LEGUMES', components: ['нут', 'вода'] },
  { foodName: 'Горох', category: 'LEGUMES', components: ['горох', 'вода'] },
  { foodName: 'Хумус', category: 'LEGUMES', components: ['нут', 'кунжутная паста', 'чеснок', 'лимонный сок'] },
  { foodName: 'Соя', category: 'LEGUMES', components: ['соевые бобы'] },
  { foodName: 'Тофу', category: 'LEGUMES', components: ['соевые бобы', 'вода'] },
  { foodName: 'Суп из чечевицы', category: 'SOUP', components: ['чечевица', 'лук', 'морковь', 'вода', 'соль'] },
  { foodName: 'Гороховый суп', category: 'SOUP', components: ['горох', 'картофель', 'лук', 'вода'] },
  { foodName: 'Фалафель', category: 'LEGUMES', components: ['нут', 'лук', 'чеснок', 'зелень', 'специи'] },

  { foodName: 'Миндаль', category: 'NUTS', components: ['миндаль'] },
  { foodName: 'Грецкий орех', category: 'NUTS', components: ['грецкий орех'] },
  { foodName: 'Фундук', category: 'NUTS', components: ['фундук'] },
  { foodName: 'Кешью', category: 'NUTS', components: ['кешью'] },
  { foodName: 'Арахис', category: 'NUTS', components: ['арахис'] },
  { foodName: 'Фисташки', category: 'NUTS', components: ['фисташки', 'соль'] },
  { foodName: 'Семечки подсолнечника', category: 'NUTS', components: ['семена подсолнечника', 'соль'] },
  { foodName: 'Тахини', category: 'NUTS', components: ['кунжут'] },
  { foodName: 'Арахисовая паста', category: 'NUTS', components: ['арахис', 'масло', 'соль'] },
  { foodName: 'Ореховый микс', category: 'NUTS', components: ['миндаль', 'фундук', 'кешью'] },

  { foodName: 'Бургер', category: 'FAST_FOOD', components: ['булка', 'котлета', 'соус', 'сыр', 'овощи'] },
  { foodName: 'Картофель фри', category: 'FAST_FOOD', components: ['картофель', 'масло', 'соль'] },
  { foodName: 'Пицца Маргарита', category: 'FAST_FOOD', components: ['тесто', 'томатный соус', 'сыр'] },
  { foodName: 'Шаурма', category: 'FAST_FOOD', components: ['лаваш', 'курица', 'овощи', 'соус'] },
  { foodName: 'Хот-дог', category: 'FAST_FOOD', components: ['булка', 'сосиска', 'соус'] },
  { foodName: 'Наггетсы', category: 'FAST_FOOD', components: ['куриное филе', 'панировка', 'масло'] },
  { foodName: 'Чипсы', category: 'FAST_FOOD', components: ['картофель', 'масло', 'соль', 'ароматизатор'] },
  { foodName: 'Сухарики', category: 'FAST_FOOD', components: ['хлеб', 'масло', 'соль', 'специи'] },
  { foodName: 'Ролл с курицей', category: 'FAST_FOOD', components: ['лаваш', 'курица', 'салат', 'соус'] },
  { foodName: 'Сэндвич', category: 'FAST_FOOD', components: ['хлеб', 'ветчина', 'сыр', 'салат'] },

  { foodName: 'Борщ', category: 'SOUP', components: ['свекла', 'капуста', 'картофель', 'морковь', 'лук'] },
  { foodName: 'Куриный суп', category: 'SOUP', components: ['курица', 'картофель', 'морковь', 'лук', 'вода'] },
  { foodName: 'Томатный суп', category: 'SOUP', components: ['томаты', 'лук', 'чеснок', 'вода'] },
  { foodName: 'Суп-пюре из брокколи', category: 'SOUP', components: ['брокколи', 'сливки', 'вода', 'соль'] },
  { foodName: 'Уха', category: 'SOUP', components: ['рыба', 'картофель', 'лук', 'вода'] },
  { foodName: 'Щи', category: 'SOUP', components: ['капуста', 'картофель', 'морковь', 'лук'] },
  { foodName: 'Рамен', category: 'SOUP', components: ['лапша', 'бульон', 'яйцо', 'соевый соус'] },
  { foodName: 'Мисо суп', category: 'SOUP', components: ['мисо паста', 'тофу', 'водоросли', 'вода'] },
  { foodName: 'Солянка', category: 'SOUP', components: ['мясо', 'огурцы', 'томат', 'оливки'] },
  { foodName: 'Грибной суп', category: 'SOUP', components: ['грибы', 'картофель', 'лук', 'вода'] },

  { foodName: 'Чай черный', category: 'BEVERAGES', components: ['вода', 'черный чай'] },
  { foodName: 'Чай зеленый', category: 'BEVERAGES', components: ['вода', 'зеленый чай'] },
  { foodName: 'Кофе американо', category: 'BEVERAGES', components: ['вода', 'кофе'] },
  { foodName: 'Капучино', category: 'BEVERAGES', components: ['эспрессо', 'молоко'] },
  { foodName: 'Латте', category: 'BEVERAGES', components: ['эспрессо', 'молоко'] },
  { foodName: 'Сок апельсиновый', category: 'BEVERAGES', components: ['апельсиновый сок'] },
  { foodName: 'Компот', category: 'BEVERAGES', components: ['вода', 'сухофрукты', 'сахар'] },
  { foodName: 'Минеральная вода', category: 'BEVERAGES', components: ['вода минеральная'] },
  { foodName: 'Газировка', category: 'BEVERAGES', components: ['вода', 'сахар', 'краситель', 'ароматизатор'] },
  { foodName: 'Какао', category: 'BEVERAGES', components: ['молоко', 'какао', 'сахар'] },
];
