spring.application.name=user-service

spring.data.mongodb.uri=mongodb://localhost:27017/health_tracker

# OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
