spring.application.name=user-service

# Internal gateway security
internal.api.secret=${INTERNAL_SECRET}

spring.data.mongodb.connection-string=${SPRING_DATA_MONGODB_URI}
logging.level.org.springframework.boot.context.properties=DEBUG
# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method