version: '3.9'

# НЕ ТРОНЬ УБЬЁТ
services:
  auth-service:
    image: 'auth-service'
    build: .
    container_name: auth-service
    restart: on-failure

    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    networks:
      - backend-net

networks:
  backend-net:
    external: true