version: '3.9'
services:
  auth-service:
    build: .
    image: n1vvas1e/auth-service:v1
    container_name: auth-service
    restart: on-failure
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/allergen_pg
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_REDIS_HOST=redis
    networks:
      - backend-net

networks:
  backend-net:
    external: true