version: '3.8'

services:

  app:
    image: allergen:1.0
    container_name: java_service
    restart: on-failure
    ports:
      - "8080:8080"
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/allergen_pg
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_DATA_MONGODB_URI: mongodb://mongo:allergen_mg@mongo:27017/admin

    networks:
      - backend-net

networks:
  backend-net:
    external: true