version: '3.9'

services:
  user-service:
    build: .
    image: n1vvas1e/user-service:v1
    container_name: user-service
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_user_db:5432/user_pg
      - SPRING_DATASOURCE_USERNAME=USER-SERVICE-POSTGRES-KOLYASKA
      - SPRING_DATASOURCE_PASSWORD=X2E1cAUfHybG8uQ2S/rg0g==
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:allergen_mg@mongo:27017/health_tracker?authSource=admin
    networks:
      - backend-net
networks:
  backend-net:
    external: true